# Consultas MDX Avanzadas con Atoti

En este notebook aprenderemos a realizar consultas MDX avanzadas utilizando Atoti y nuestro esquema universitario.

## 1. Configuración Inicial

Importamos las bibliotecas necesarias e iniciamos una sesión:

In [1]:
import atoti as tt
import pandas as pd
import numpy as np

session = tt.Session.start()

Welcome to Atoti 0.9.5!

By using this community edition, you agree with the license available at https://docs.atoti.io/latest/eula.html.
Browse the official documentation at https://docs.atoti.io.
Join the community at https://www.atoti.io/register.

Atoti collects telemetry data, which is used to help understand how to improve the product.
If you don't wish to send usage data, you can request a trial license at https://www.atoti.io/evaluation-license-request.

You can hide this message by setting the `ATOTI_HIDE_EULA_MESSAGE` environment variable to True.

## 2. Crear Datos de Ejemplo Complejos

Vamos a crear un conjunto de datos más complejo que incluya información sobre matrículas, rendimiento y docencia:

In [3]:
# Datos de matrículas y rendimiento
data = {
    'CursoAcademico': ['2023/2024'] * 24 + ['2022/2023'] * 24,
    'Centro': ['Facultad de Ciencias'] * 12 + ['Facultad de Letras'] * 12 + ['Facultad de Ciencias'] * 12 + ['Facultad de Letras'] * 12,
    'PlanEstudio': ['Grado en Informática', 'Grado en Matemáticas', 'Grado en Física', 
                   'Grado en Filología', 'Grado en Historia', 'Grado en Filosofía'] * 8,
    'NumeroMatriculados': [120, 80, 60, 90, 70, 50] * 8,
    'CreditosMatriculados': [7200, 4800, 3600, 5400, 4200, 3000] * 8,
    'TasaAprobados': [0.85, 0.82, 0.80, 0.90, 0.88, 0.85] * 8,
    'NumeroProfesores': [2, 2, 2, 2, 2, 2] * 8
}

df = pd.DataFrame(data)
df

,CursoAcademico,Centro,PlanEstudio,NumeroMatriculados,CreditosMatriculados,TasaAprobados,NumeroProfesores
0,2023/2024,Facultad de Ciencias,Grado en Informática,120,7200,0.85,2
1,2023/2024,Facultad de Ciencias,Grado en Matemáticas,80,4800,0.82,2
2,2023/2024,Facultad de Ciencias,Grado en Física,60,3600,0.80,2
3,2023/2024,Facultad de Ciencias,Grado en Filología,90,5400,0.90,2
4,2023/2024,Facultad de Ciencias,Grado en Historia,70,4200,0.88,2
5,2023/2024,Facultad de Ciencias,Grado en Filosofía,50,3000,0.85,2
6,2023/2024,Facultad de Ciencias,Grado en Informática,120,7200,0.85,2
7,2023/2024,Facultad de Ciencias,Grado en Matemáticas,80,4800,0.82,2
8,2023/2024,Facultad de Ciencias,Grado en Física,60,3600,0.80,2
9,2023/2024,Facultad de Ciencias,Grado en Filología,90,5400,0.90,2
10,2023/2024,Facultad de Ciencias,Grado en Historia,70,4200,0.88,2
11,2023/2024,Facultad de Ciencias,Grado en Filosofía,50,3000,0.85,2
12,2023/2024,Facultad de Letras,Grado en Informática,120,7200,0.85,2
13,2023/2024,Facultad de Letras,Grado en Matemáticas,80,4800,0.82,2
14,2023/2024,Facultad de Letras,Grado en Física,60,3600,0.80,2
15,2023/2024,Facultad de Letras,Grado en Filología,90,5400,0.90,2
16,2023/2024,Facultad de Letras,Grado en Historia,70,4200,0.88,2
17,2023/2024,Facultad de Letras,Grado en Filosofía,50,3000,0.85,2
18,2023/2024,Facultad de Letras,Grado en Informática,120,7200,0.85,2
19,2023/2024,Facultad de Letras,Grado en Matemáticas,80,4800,0.82,2
20,2023/2024,Facultad de Letras,Grado en Física,60,3600,0.80,2
21,2023/2024,Facultad de Letras,Grado en Filología,90,5400,0.90,2
22,2023/2024,Facultad de Letras,Grado en Historia,70,4200,0.88,2
23,2023/2024,Facultad de Letras,Grado en Filosofía,50,3000,0.85,2
24,2022/2023,Facultad de Ciencias,Grado en Informática,120,7200,0.85,2
25,2022/2023,Facultad de Ciencias,Grado en Matemáticas,80,4800,0.82,2
26,2022/2023,Facultad de Ciencias,Grado en Física,60,3600,0.80,2
27,2022/2023,Facultad de Ciencias,Grado en Filología,90,5400,0.90,2
28,2022/2023,Facultad de Ciencias,Grado en Historia,70,4200,0.88,2
29,2022/2023,Facultad de Ciencias,Grado en Filosofía,50,3000,0.85,2
30,2022/2023,Facultad de Ciencias,Grado en Informática,120,7200,0.85,2
31,2022/2023,Facultad de Ciencias,Grado en Matemáticas,80,4800,0.82,2
32,2022/2023,Facultad de Ciencias,Grado en Física,60,3600,0.80,2
33,2022/2023,Facultad de Ciencias,Grado en Filología,90,5400,0.90,2
34,2022/2023,Facultad de Ciencias,Grado en Historia,70,4200,0.88,2
35,2022/2023,Facultad de Ciencias,Grado en Filosofía,50,3000,0.85,2
36,2022/2023,Facultad de Letras,Grado en Informática,120,7200,0.85,2
37,2022/2023,Facultad de Letras,Grado en Matemáticas,80,4800,0.82,2
38,2022/2023,Facultad de Letras,Grado en Física,60,3600,0.80,2
39,2022/2023,Facultad de Letras,Grado en Filología,90,5400,0.90,2
40,2022/2023,Facultad de Letras,Grado en Historia,70,4200,0.88,2
41,2022/2023,Facultad de Letras,Grado en Filosofía,50,3000,0.85,2
42,2022/2023,Facultad de Letras,Grado en Informática,120,7200,0.85,2
43,2022/2023,Facultad de Letras,Grado en Matemáticas,80,4800,0.82,2
44,2022/2023,Facultad de Letras,Grado en Física,60,3600,0.80,2
45,2022/2023,Facultad de Letras,Grado en Filología,90,5400,0.90,2
46,2022/2023,Facultad de Letras,Grado en Historia,70,4200,0.88,2
47,2022/2023,Facultad de Letras,Grado en Filosofía,50,3000,0.85,2

## 3. Crear Tabla y Cubo

Cargamos los datos en una tabla de Atoti y creamos un cubo:

In [5]:
# Crear tabla
academico_table = session.read_pandas(
    df,
    table_name="Academico",
    keys=["CursoAcademico", "Centro", "PlanEstudio"]  
)

# Crear cubo
cube = session.create_cube(academico_table)

## 4. Consultas MDX Avanzadas

### 4.1 Consulta con Agrupación y Ordenación

Vamos a crear una consulta que agrupe y ordene los datos:

In [8]:
# Consulta con agrupación y ordenación
cube.query(
    cube.measures["NumeroMatriculados.SUM"],
    levels=[
        cube.hierarchies["Centro"]["Centro"],
        cube.hierarchies["PlanEstudio"]["PlanEstudio"]
    ],
    filter=cube.hierarchies["CursoAcademico"].["CursoAcademico"] == "2023/2024"
).sort_values(by="NumeroMatriculados.SUM", ascending=False)

C:\Users\theca\AppData\Local\Temp\ipykernel_19424\4217691286.py:5: FutureWarning: `Hierarchy.levels` is deprecated, iterate on the hierarchy instead.
  cube.hierarchies["Centro"].levels["Centro"],
C:\Users\theca\AppData\Local\Temp\ipykernel_19424\4217691286.py:6: FutureWarning: `Hierarchy.levels` is deprecated, iterate on the hierarchy instead.
  cube.hierarchies["PlanEstudio"].levels["PlanEstudio"]
C:\Users\theca\AppData\Local\Temp\ipykernel_19424\4217691286.py:8: FutureWarning: `Hierarchy.levels` is deprecated, iterate on the hierarchy instead.
  filter=cube.hierarchies["CursoAcademico"].levels["CursoAcademico"] == "2023/2024"

                                           NumeroMatriculados.SUM
Centro               PlanEstudio
Facultad de Letras   Grado en Informática                     120
Facultad de Ciencias Grado en Informática                     120
                     Grado en Filología                        90
Facultad de Letras   Grado en Filología                        90
                     Grado en Matemáticas                      80
Facultad de Ciencias Grado en Matemáticas                      80
                     Grado en Historia                         70
Facultad de Letras   Grado en Historia                         70
                     Grado en Física                           60
Facultad de Ciencias Grado en Física                           60
                     Grado en Filosofía                        50
Facultad de Letras   Grado en Filosofía                        50

### 4.2 Consulta con múltiples filtros

Vamos a crear una consulta con múltiples condiciones de filtrado:

In [14]:
# Consulta con múltiples filtros
cube.query(
    cube.measures["NumeroMatriculados.SUM"],
    cube.measures["TasaAprobados.MEAN"],
    levels=[
        cube.hierarchies["Centro"]["Centro"],
        cube.hierarchies["PlanEstudio"]["PlanEstudio"]
    ],
    filter=(
        (cube.hierarchies["CursoAcademico"]["CursoAcademico"] == "2023/2024") & 
        (cube.measures["TasaAprobados.MEAN"] > 0.8)
    )
)

                                          NumeroMatriculados.SUM  \
Centro               PlanEstudio
Facultad de Ciencias Grado en Filología                       90
                     Grado en Filosofía                       50
                     Grado en Historia                        70
                     Grado en Informática                    120
                     Grado en Matemáticas                     80
Facultad de Letras   Grado en Filología                       90
                     Grado en Filosofía                       50
                     Grado en Historia                        70
                     Grado en Informática                    120
                     Grado en Matemáticas                     80

                                          TasaAprobados.MEAN
Centro               PlanEstudio
Facultad de Ciencias Grado en Filología                  .90
                     Grado en Filosofía                  .85
                     Grado en Historia                   .88
                     Grado en Informática                .85
                     Grado en Matemáticas                .82
Facultad de Letras   Grado en Filología                  .90
                     Grado en Filosofía                  .85
                     Grado en Historia                   .88
                     Grado en Informática                .85
                     Grado en Matemáticas                .82

### 4.3 Consulta con medidas calculadas avanzadas

Vamos a crear algunas medidas calculadas más complejas:

In [19]:
# Medida para la eficiencia docente (usando créditos en lugar de horas)
cube.measures["Eficiencia Docente"] = (
    cube.measures["TasaAprobados.MEAN"] / 
    (cube.measures["CreditosMatriculados.SUM"] / cube.measures["NumeroMatriculados.SUM"])
)

# Medida para la carga docente por profesor (usando créditos en lugar de horas)
cube.measures["Carga Docente por Profesor"] = (
    cube.measures["CreditosMatriculados.SUM"] / cube.measures["NumeroProfesores.SUM"]
)

# Medida para la tasa de éxito ponderada (usando solo tasa de aprobados)
cube.measures["Tasa Exito Ponderada"] = (
    cube.measures["TasaAprobados.MEAN"] * cube.measures["NumeroMatriculados.SUM"] / 100
)

### 4.4 Consulta con medidas calculadas

Vamos a usar nuestras nuevas medidas calculadas:

In [22]:
# Consulta con medidas calculadas
cube.query(
    cube.measures["Eficiencia Docente"],
    cube.measures["Carga Docente por Profesor"],
    cube.measures["Tasa Exito Ponderada"],
    levels=[
        cube.hierarchies["Centro"]["Centro"],
        cube.hierarchies["PlanEstudio"]["PlanEstudio"]
    ],
    filter=cube.hierarchies["CursoAcademico"]["CursoAcademico"] == "2023/2024"
)

                                          Eficiencia Docente  \
Centro               PlanEstudio
Facultad de Ciencias Grado en Filología                  .02
                     Grado en Filosofía                  .01
                     Grado en Física                     .01
                     Grado en Historia                   .01
                     Grado en Informática                .01
                     Grado en Matemáticas                .01
Facultad de Letras   Grado en Filología                  .02
                     Grado en Filosofía                  .01
                     Grado en Física                     .01
                     Grado en Historia                   .01
                     Grado en Informática                .01
                     Grado en Matemáticas                .01

                                          Carga Docente por Profesor  \
Centro               PlanEstudio
Facultad de Ciencias Grado en Filología                     2,700.00
                     Grado en Filosofía                     1,500.00
                     Grado en Física                        1,800.00
                     Grado en Historia                      2,100.00
                     Grado en Informática                   3,600.00
                     Grado en Matemáticas                   2,400.00
Facultad de Letras   Grado en Filología                     2,700.00
                     Grado en Filosofía                     1,500.00
                     Grado en Física                        1,800.00
                     Grado en Historia                      2,100.00
                     Grado en Informática                   3,600.00
                     Grado en Matemáticas                   2,400.00

                                          Tasa Exito Ponderada
Centro               PlanEstudio
Facultad de Ciencias Grado en Filología                    .81
                     Grado en Filosofía                    .42
                     Grado en Física                       .48
                     Grado en Historia                     .62
                     Grado en Informática                 1.02
                     Grado en Matemáticas                  .66
Facultad de Letras   Grado en Filología                    .81
                     Grado en Filosofía                    .42
                     Grado en Física                       .48
                     Grado en Historia                     .62
                     Grado en Informática                 1.02
                     Grado en Matemáticas                  .66

### 4.5 Consulta con agregaciones personalizadas

Vamos a crear una consulta con agregaciones personalizadas:

In [33]:
# Medida para el rendimiento relativo
cube.measures["Rendimiento Relativo"] = (
    cube.measures["TasaAprobados.MEAN"] / 
    tt.agg.mean(cube.measures["TasaAprobados.MEAN"], scope=tt.OriginScope(levels=[cube.hierarchies["Centro"]["Centro"]]))
)

# Consulta con agregación personalizada
cube.query(
    cube.measures["Rendimiento Relativo"],
    cube.measures["Tasa Exito Ponderada"],
    levels=[
        cube.hierarchies["Centro"]["Centro"],
        cube.hierarchies["PlanEstudio"]["PlanEstudio"]
    ],
    filter=cube.hierarchies["CursoAcademico"]["CursoAcademico"] == "2023/2024"
).sort_values(by="Rendimiento Relativo", ascending=False)

                                           Rendimiento Relativo  \
Centro               PlanEstudio
Facultad de Ciencias Grado en Filología                     1.0
                     Grado en Filosofía                     1.0
                     Grado en Física                        1.0
                     Grado en Historia                      1.0
                     Grado en Informática                   1.0
                     Grado en Matemáticas                   1.0
Facultad de Letras   Grado en Filología                     1.0
                     Grado en Filosofía                     1.0
                     Grado en Física                        1.0
                     Grado en Historia                      1.0
                     Grado en Informática                   1.0
                     Grado en Matemáticas                   1.0

                                           Tasa Exito Ponderada
Centro               PlanEstudio
Facultad de Ciencias Grado en Filología                    0.81
                     Grado en Filosofía                   0.425
                     Grado en Física                       0.48
                     Grado en Historia                    0.616
                     Grado en Informática                  1.02
                     Grado en Matemáticas                 0.656
Facultad de Letras   Grado en Filología                    0.81
                     Grado en Filosofía                   0.425
                     Grado en Física                       0.48
                     Grado en Historia                    0.616
                     Grado en Informática                  1.02
                     Grado en Matemáticas                 0.656

## 5. Crear un dashboard avanzado

Vamos a crear un dashboard interactivo que muestre diferentes aspectos de los datos:

In [ ]:
session.widget

## Ejercicios prácticos

1. Crea una medida calculada que muestre la evolución del rendimiento entre semestres
2. Realiza una consulta que compare la eficiencia docente entre diferentes centros
3. Crea una medida que calcule la tasa de éxito ajustada por la carga docente
4. Implementa un dashboard que muestre la relación entre número de profesores y rendimiento académico