# 📊 Introducción a Atoti y Consultas MDX

Bienvenido a este tutorial completo sobre **Atoti** y las consultas **MDX** (MultiDimensional eXpressions). Este notebook está diseñado para usuarios de diferentes niveles de experiencia.

## 🎯 Objetivos del Notebook
- Comprender qué es Atoti y cómo funciona el análisis multidimensional
- Aprender los fundamentos de las consultas MDX
- Crear cubos OLAP con datos académicos reales
- Realizar visualizaciones interactivas

## 📚 Estructura por Niveles
- **🔰 NIVEL BÁSICO**: Conceptos fundamentales con explicaciones detalladas
- **🚀 NIVEL AVANZADO**: Técnicas complejas y optimizaciones

---

## 🔰 ¿Qué es MDX?
**MDX** es un lenguaje de consulta para bases de datos multidimensionales (cubos OLAP). Piensa en él como "SQL para cubos":

- **SQL**: Trabaja con tablas planas (filas y columnas)
- **MDX**: Trabaja con cubos multidimensionales (dimensiones, jerarquías, medidas)

**Analogía**: Si SQL es como buscar información en una hoja de Excel, MDX es como analizar datos en una tabla dinámica 3D.

## ⚙️ Configuración Inicial

Configuraremos la conexión a nuestra base de datos Oracle con el esquema `DM_ACADEMICO`.

In [1]:
# Importaciones necesarias
import atoti as tt
from atoti_jdbc import JdbcLoad
import os
import pandas as pd

# 🔰 BÁSICO: Configuración de conexión a Oracle
ORACLE_USER = os.getenv('ORACLE_USER', 'C##DM_ACADEMICO')
ORACLE_PASSWORD = os.getenv('ORACLE_PASSWORD', 'YourPassword123')
ORACLE_HOST = os.getenv('ORACLE_HOST', 'localhost')
ORACLE_PORT = os.getenv('ORACLE_PORT', '1521')
ORACLE_SERVICE = os.getenv('ORACLE_SERVICE', 'XEPDB1')

# Crear URL de conexión JDBC
jdbc_url = f"jdbc:oracle:thin:{ORACLE_USER}/{ORACLE_PASSWORD}@//{ORACLE_HOST}:{ORACLE_PORT}/{ORACLE_SERVICE}"

print("✅ Configuración de conexión completada")
print(f"🔗 Conectando a: {ORACLE_HOST}:{ORACLE_PORT}/{ORACLE_SERVICE}")

Welcome to Atoti 0.9.5!

By using this community edition, you agree with the license available at https://docs.atoti.io/latest/eula.html.
Browse the official documentation at https://docs.atoti.io.
Join the community at https://www.atoti.io/register.

Atoti collects telemetry data, which is used to help understand how to improve the product.
If you don't wish to send usage data, you can request a trial license at https://www.atoti.io/evaluation-license-request.

You can hide this message by setting the `ATOTI_HIDE_EULA_MESSAGE` environment variable to True.
✅ Configuración de conexión completada
🔗 Conectando a: localhost:1521/XEPDB1

In [108]:
# Cerrar todas las sesiones
try:
    if 'session' in globals():
        session.close()
        del globals
        print("✅ Sesión anterior cerrada")
except:
    pass


# Iniciar sesión de Atoti
session = tt.Session.start()
print("🚀 Sesión de Atoti iniciada correctamente")
print(f"📍 URL del servidor: {session.url}")

🚀 Sesión de Atoti iniciada correctamente
📍 URL del servidor: http://localhost:52478

## 🔰 NIVEL BÁSICO - Primeros Pasos

### 📖 Conceptos Fundamentales

Antes de crear nuestro primer cubo, entendamos los conceptos básicos:

- **🎯 Medidas**: Valores numéricos que queremos analizar (ej: número de estudiantes, promedio de notas)
- **📊 Dimensiones**: Categorías para agrupar datos (ej: carrera, año académico, género)
- **🏗️ Jerarquías**: Niveles dentro de una dimensión (ej: Año > Semestre > Mes)
- **🧊 Cubo**: Estructura que organiza medidas y dimensiones para análisis

In [109]:
# 🔰 FUNCIÓN AUXILIAR CORREGIDA: Cargar tablas de forma segura
def cargar_tabla_academica(nombre_tabla, query_sql, claves_primarias):
    """
    Carga una tabla desde Oracle con validaciones automáticas.
    
    Args:
        nombre_tabla (str): Nombre para la tabla en Atoti
        query_sql (str): Consulta SQL para obtener los datos
        claves_primarias (set): Conjunto de columnas que forman la clave primaria
    
    Returns:
        Tabla de Atoti con los datos cargados
    """
    try:
        # Crear carga JDBC
        jdbc_load = JdbcLoad(query_sql, url=jdbc_url)
        
        # Inferir tipos de datos automáticamente
        data_types = session.tables.infer_data_types(jdbc_load)
        print(f"📋 Tipos de datos inferidos para {nombre_tabla}")
        
        # Crear tabla en Atoti
        tabla = session.create_table(
            nombre_tabla, 
            data_types=data_types, 
            keys=claves_primarias
        )
        
        # Cargar datos
        tabla.load(jdbc_load)
        
        print(f"✅ Tabla {nombre_tabla} cargada exitosamente")
        
        # 🔧 CORRECCIÓN: Usar len() en lugar de shape
        try:
            num_registros = len(tabla)
            print(f"📊 Registros cargados: {num_registros}")
        except:
            # Alternativa si len() no funciona
            print("📊 Datos cargados (conteo no disponible)")
        
        return tabla
        
    except Exception as e:
        print(f"❌ Error cargando {nombre_tabla}: {str(e)}")
        return None

### 📚 Cargando Nuestros Primeros Datos

Comenzaremos con las tablas más importantes del esquema académico:

In [110]:
# 🔰 CARGAR TABLA DE HECHOS: Matrículas
print("📚 Cargando tabla de matrículas (hechos principales)...")
tabla_matriculas = cargar_tabla_academica(
    "Matriculas",
    "SELECT * FROM F_MATRICULA WHERE ROWNUM <= 1000",  # Limitamos para el ejemplo
    {"ID_ALUMNO", "ID_CURSO_ACADEMICO", "ID_ASIGNATURA"}
)

# 🔰 CARGAR DIMENSIÓN: Cursos Académicos
print("\n📅 Cargando dimensión de cursos académicos...")
tabla_cursos = cargar_tabla_academica(
    "CursosAcademicos",
    "SELECT * FROM D_CURSO_ACADEMICO",
    {"ID_CURSO_ACADEMICO"}
)

# 🔰 CARGAR DIMENSIÓN: Sexo
print("\n👤 Cargando dimensión de sexo...")
tabla_sexo = cargar_tabla_academica(
    "Sexo",
    "SELECT * FROM D_SEXO",
    {"ID_SEXO"}
)

# Verificar que las tablas se cargaron correctamente
if tabla_matriculas and tabla_cursos and tabla_sexo:
    print("\n🎉 ¡Todas las tablas básicas cargadas exitosamente!")
else:
    print("\n⚠️ Algunas tablas no se pudieron cargar. Verificar conexión y esquema.")

📚 Cargando tabla de matrículas (hechos principales)...
📋 Tipos de datos inferidos para Matriculas
✅ Tabla Matriculas cargada exitosamente
📊 Datos cargados (conteo no disponible)

📅 Cargando dimensión de cursos académicos...
📋 Tipos de datos inferidos para CursosAcademicos
✅ Tabla CursosAcademicos cargada exitosamente
📊 Datos cargados (conteo no disponible)

👤 Cargando dimensión de sexo...
📋 Tipos de datos inferidos para Sexo
✅ Tabla Sexo cargada exitosamente
📊 Datos cargados (conteo no disponible)

🎉 ¡Todas las tablas básicas cargadas exitosamente!

### 🧊 Creando Nuestro Primer Cubo

Un cubo es como una "tabla dinámica super potente" que nos permite analizar datos desde múltiples perspectivas.

In [111]:
# 🔰 CREAR CUBO BÁSICO 
if tabla_matriculas:
    # Unir tabla de hechos con dimensiones usando la sintaxis correcta
    if tabla_cursos:
        tabla_matriculas.join(
            tabla_cursos,
            tabla_matriculas["ID_CURSO_ACADEMICO"] == tabla_cursos["ID_CURSO_ACADEMICO"]
        )
        print("🔗 Unión con cursos académicos realizada")
    
    if tabla_sexo:
        tabla_matriculas.join(
            tabla_sexo,
            tabla_matriculas["ID_SEXO"] == tabla_sexo["ID_SEXO"]
        )
        print("🔗 Unión con dimensión sexo realizada")
    
    # Crear el cubo
    cubo_academico = session.create_cube(tabla_matriculas, "CuboAcademico")
    
    print("\n🧊 ¡Cubo académico creado exitosamente!")
    
    # Obtener referencias a jerarquías, niveles y medidas
    h = cubo_academico.hierarchies  # Jerarquías
    l = cubo_academico.levels      # Niveles
    m = cubo_academico.measures    # Medidas
    
    print(f"📊 Jerarquías disponibles: {len(h)}")
    print(f"📈 Medidas automáticas: {len(m)}")

🔗 Unión con cursos académicos realizada
🔗 Unión con dimensión sexo realizada

🧊 ¡Cubo académico creado exitosamente!
📊 Jerarquías disponibles: 37
📈 Medidas automáticas: 134

In [22]:
# 🔰 EXPLORAR LA ESTRUCTURA DEL CUBO
if 'cubo_academico' in locals():
    print("🔍 EXPLORANDO NUESTRO CUBO:")
    print("\n📊 JERARQUÍAS DISPONIBLES:")
    for nombre_jerarquia in sorted(h.keys())[:5]:  # Mostramos solo las primeras 5
        print(f"  📁 {nombre_jerarquia}")
    
    print("\n📈 MEDIDAS AUTOMÁTICAS:")
    for nombre_medida in sorted(m.keys())[:5]:  # Mostramos solo las primeras 5
        print(f"  📊 {nombre_medida}")
    
    # Crear medidas personalizadas más comprensibles
    print("\n🎯 CREANDO MEDIDAS PERSONALIZADAS:")
    
    # Medida: Número total de estudiantes únicos
    m["Total_Estudiantes"] = tt.agg.count_distinct(tabla_matriculas["ID_ALUMNO"])
    print("  ✅ Total_Estudiantes: Cuenta estudiantes únicos")
    
    # Medida: Promedio de estudiantes por curso (medida calculada)
    m["Avg_Estudiantes_Por_Curso"] = m["Total_Estudiantes"] / tt.agg.count_distinct(tabla_matriculas["ID_CURSO_ACADEMICO"])
    print("  ✅ Avg_Estudiantes_Por_Curso: Promedio de estudiantes por curso")
    
    print("\n🎉 ¡Cubo listo para consultas!")
    
    # Mostrar todas las medidas disponibles
    print(f"\n📋 Total de medidas en el cubo: {len(m)}")
    print("🔢 Medidas principales:")
    for medida in ["Total_Estudiantes", "Total_Matriculas", "contributors.COUNT"]:
        if medida in m:
            print(f"  ✓ {medida}")

🔍 EXPLORANDO NUESTRO CUBO:

📊 JERARQUÍAS DISPONIBLES:
  📁 ('CursosAcademicos', 'NOMBRE_CURSO_ACADEMICO')
  📁 ('Matriculas', 'COD_POSTAL_CURSO')
  📁 ('Matriculas', 'COD_POSTAL_FAMILIAR')
  📁 ('Matriculas', 'CURSO_IMPARTICION_ASIG')
  📁 ('Matriculas', 'CURSO_ORDEN')

📈 MEDIDAS AUTOMÁTICAS:
  📊 ANYO_ACCESO_SUE.MEAN
  📊 ANYO_ACCESO_SUE.SUM
  📊 CREDITOS.MEAN
  📊 CREDITOS.SUM
  📊 CURSO_MAS_ALTO_MATRICULADO.MEAN

🎯 CREANDO MEDIDAS PERSONALIZADAS:
  ✅ Total_Estudiantes: Cuenta estudiantes únicos
  ✅ Avg_Estudiantes_Por_Curso: Promedio de estudiantes por curso

🎉 ¡Cubo listo para consultas!

📋 Total de medidas en el cubo: 137
🔢 Medidas principales:
  ✓ Total_Estudiantes
  ✓ contributors.COUNT

### 🔍 Nuestras Primeras Consultas MDX

Una consulta MDX básica tiene esta estructura:
```python
cubo.query(
    medida_que_queremos,           # ¿Qué queremos medir?
    levels=[dimensión_para_agrupar] # ¿Cómo queremos agrupar?
)
```

In [23]:
# 🔰 CONSULTA 1: ¿Cuántos estudiantes tenemos en total?
if 'cubo_academico' in locals():
    print("🔍 CONSULTA 1: Total de estudiantes")
    print("📝 Pregunta: ¿Cuántos estudiantes únicos hay en total?")
    
    try:
        resultado1 = cubo_academico.query(m["Total_Estudiantes"])
        print("✅ Resultado:")
        display(resultado1)
        
        print("\n💡 Explicación:")
        print("   - Usamos la medida 'Total_Estudiantes'")
        print("   - No especificamos niveles, así que obtenemos el total general")
        print("   - count_distinct() evita contar el mismo estudiante varias veces")
        
    except Exception as e:
        print(f"❌ Error en consulta: {e}")

🔍 CONSULTA 1: Total de estudiantes
📝 Pregunta: ¿Cuántos estudiantes únicos hay en total?
✅ Resultado:

  Total_Estudiantes
0                99

💡 Explicación:
   - Usamos la medida 'Total_Estudiantes'
   - No especificamos niveles, así que obtenemos el total general
   - count_distinct() evita contar el mismo estudiante varias veces

In [29]:
# 🔰 CONSULTA 2: ¿Cuántos estudiantes hay por sexo? - CORREGIDO
if 'cubo_academico' in locals():
    print("🔍 CONSULTA 2: Estudiantes por sexo")
    print("📝 Pregunta: ¿Cómo se distribuyen los estudiantes por género?")
    
    try:
        # Obtener el nivel de sexo directamente
        nivel_sexo_key = ('Sexo', 'NOMBRE_SEXO', 'NOMBRE_SEXO')
        
        # CORRECCIÓN: No usar if nivel_sexo directamente, sino verificar si la key existe
        if nivel_sexo_key in l:
            nivel_sexo = l[nivel_sexo_key]
            print(f"🎯 Usando nivel de sexo: {nivel_sexo_key}")
            
            # Realizar la consulta
            resultado2 = cubo_academico.query(
                m["Total_Estudiantes"],
                levels=[nivel_sexo]
            )
            
            print("✅ Resultado - Estudiantes por sexo:")
            display(resultado2)
            
            print("\n💡 Explicación:")
            print("   - levels=[nivel_sexo]: Agrupa los resultados por género")
            print("   - Cada fila muestra el total de estudiantes para ese género")
            print("   - Esta es la base del análisis dimensional")
            
        else:
            print("⚠️ Nivel NOMBRE_SEXO no disponible, probando alternativas...")
            
            # Alternativa 1: Campo SEXO de Matriculas
            nivel_sexo_alt_key = ('Matriculas', 'SEXO', 'SEXO')
            if nivel_sexo_alt_key in l:
                nivel_sexo_alt = l[nivel_sexo_alt_key]
                print(f"🔄 Usando nivel alternativo: {nivel_sexo_alt_key}")
                
                resultado2_alt = cubo_academico.query(
                    m["Total_Estudiantes"],
                    levels=[nivel_sexo_alt]
                )
                
                print("✅ Resultado alternativo - Estudiantes por sexo:")
                display(resultado2_alt)
                
            else:
                # Alternativa 2: Agrupar por curso académico
                nivel_curso_key = ('CursosAcademicos', 'NOMBRE_CURSO_ACADEMICO', 'NOMBRE_CURSO_ACADEMICO')
                if nivel_curso_key in l:
                    nivel_curso = l[nivel_curso_key]
                    print(f"🔄 Agrupando por curso académico: {nivel_curso_key}")
                    
                    resultado_curso = cubo_academico.query(
                        m["Total_Estudiantes"],
                        levels=[nivel_curso]
                    )
                    
                    print("✅ Resultado - Estudiantes por curso académico:")
                    display(resultado_curso)
                else:
                    print("❌ No se encontraron niveles válidos para agrupar")
        
    except Exception as e:
        print(f"❌ Error en consulta: {str(e)}")
        
        # Consulta de respaldo más simple
        print("\n🆘 Intentando consulta más simple...")
        try:
            resultado_backup = cubo_academico.query(m["Total_Estudiantes"])
            print("✅ Total general de estudiantes:")
            display(resultado_backup)
        except Exception as e2:
            print(f"❌ Error en consulta de respaldo: {str(e2)}")

🔍 CONSULTA 2: Estudiantes por sexo
📝 Pregunta: ¿Cómo se distribuyen los estudiantes por género?
🎯 Usando nivel de sexo: ('Sexo', 'NOMBRE_SEXO', 'NOMBRE_SEXO')
✅ Resultado - Estudiantes por sexo:

            Total_Estudiantes
NOMBRE_SEXO
Hombre                     52
Mujer                      47

💡 Explicación:
   - levels=[nivel_sexo]: Agrupa los resultados por género
   - Cada fila muestra el total de estudiantes para ese género
   - Esta es la base del análisis dimensional

### 📊 Visualización Interactiva Básica

Atoti incluye widgets interactivos que nos permiten explorar datos de forma visual.

In [30]:
# 🔰 WIDGET INTERACTIVO BÁSICO
print("🎨 Creando visualización interactiva...")
print("\n📖 INSTRUCCIONES:")
print("  1. Arrastra medidas desde el panel izquierdo")
print("  2. Arrastra dimensiones para crear gráficos")
print("  3. Experimenta con diferentes combinaciones")

# Mostrar widget interactivo
session.widget

🎨 Creando visualización interactiva...

📖 INSTRUCCIONES:
  1. Arrastra medidas desde el panel izquierdo
  2. Arrastra dimensiones para crear gráficos
  3. Experimenta con diferentes combinaciones

Open the notebook in JupyterLab with the Atoti JupyterLab extension enabled to build this widget.

---

## 🚀 NIVEL AVANZADO - Técnicas Especializadas

### 🏗️ Cubos Complejos con Múltiples Dimensiones

Para usuarios avanzados, crearemos un cubo más sofisticado que integre múltiples tablas de hechos y dimensiones.

In [72]:
# Cerrar todas las sesiones
try:
    if 'session' in globals():
        session.close()
        del globals
        print("✅ Sesión anterior cerrada")
except:
    pass


# Iniciar sesión de Atoti
session = tt.Session.start()
print("🚀 Sesión de Atoti iniciada correctamente")
print(f"📍 URL del servidor: {session.url}")

🔄 Realizando reinicio completo del entorno...
✅ Sesión anterior cerrada
🚀 Nueva sesión iniciada en: http://localhost:51679

In [73]:
# 🚀 CARGAR DATOS ADICIONALES PARA ANÁLISIS AVANZADO
print("🚀 NIVEL AVANZADO: Cargando datos adicionales...")

# Cargar tabla de rendimiento académico
tabla_rendimiento = cargar_tabla_academica(
    "Rendimiento",
    "SELECT * FROM F_RENDIMIENTO WHERE ROWNUM <= 1000",
    {"ID_ALUMNO", "ID_ASIGNATURA", "ID_CURSO_ACADEMICO"}
)

# Cargar dimensión de asignaturas
tabla_asignaturas = cargar_tabla_academica(
    "Asignaturas",
    "SELECT * FROM D_ASIGNATURA",
    {"ID_ASIGNATURA"}
)

# Cargar dimensión de calificaciones
tabla_calificaciones = cargar_tabla_academica(
    "Calificaciones",
    "SELECT * FROM D_CALIFICACION",
    {"ID_CALIFICACION"}
)


# Cargar dimensión de cursos
tabla_cursos = cargar_tabla_academica(
    "CursosAcademicos",
    "SELECT * FROM D_CURSO_ACADEMICO",
    {"ID_CURSO_ACADEMICO"}
)

print("\n✅ Datos avanzados cargados para análisis de rendimiento")

🚀 NIVEL AVANZADO: Cargando datos adicionales...
📋 Tipos de datos inferidos para Rendimiento
✅ Tabla Rendimiento cargada exitosamente
📊 Datos cargados (conteo no disponible)
📋 Tipos de datos inferidos para Asignaturas
✅ Tabla Asignaturas cargada exitosamente
📊 Datos cargados (conteo no disponible)
📋 Tipos de datos inferidos para Calificaciones
✅ Tabla Calificaciones cargada exitosamente
📊 Datos cargados (conteo no disponible)
📋 Tipos de datos inferidos para CursosAcademicos
✅ Tabla CursosAcademicos cargada exitosamente
📊 Datos cargados (conteo no disponible)

✅ Datos avanzados cargados para análisis de rendimiento

In [74]:
# 🚀 CREAR CUBO AVANZADO DE RENDIMIENTO
if tabla_rendimiento:
    print("🚀 Creando cubo avanzado de rendimiento académico...")
    
    # Unir con dimensiones relacionadas usando la sintaxis correcta
    if tabla_asignaturas:
        tabla_rendimiento.join(
            tabla_asignaturas,
            tabla_rendimiento["ID_ASIGNATURA"] == tabla_asignaturas["ID_ASIGNATURA"]
        )
        print("🔗 Dimensión de asignaturas vinculada")
    
    if tabla_calificaciones:
        tabla_rendimiento.join(
            tabla_calificaciones,
            tabla_rendimiento["ID_CALIFICACION"] == tabla_calificaciones["ID_CALIFICACION"]
        )
        print("🔗 Dimensión de calificaciones vinculada")
    
    if tabla_cursos:
        tabla_rendimiento.join(
            tabla_cursos,
            tabla_rendimiento["ID_CURSO_ACADEMICO"] == tabla_cursos["ID_CURSO_ACADEMICO"]
        )
        print("🔗 Dimensión temporal vinculada")
    
    # Crear cubo avanzado
    cubo_rendimiento = session.create_cube(tabla_rendimiento, "CuboRendimiento")
    
    # Referencias para el cubo avanzado
    h_adv = cubo_rendimiento.hierarchies
    l_adv = cubo_rendimiento.levels
    m_adv = cubo_rendimiento.measures
    
    print("\n🧊 Cubo avanzado de rendimiento creado")
    print(f"📊 Jerarquías: {len(h_adv)}")
    print(f"📈 Medidas: {len(m_adv)}")

🚀 Creando cubo avanzado de rendimiento académico...
🔗 Dimensión de asignaturas vinculada
🔗 Dimensión de calificaciones vinculada
🔗 Dimensión temporal vinculada

🧊 Cubo avanzado de rendimiento creado
📊 Jerarquías: 19
📈 Medidas: 124

In [94]:
# 🚀 MEDIDAS CALCULADAS AVANZADAS
if 'cubo_rendimiento' in locals():
    print("🚀 Creando medidas calculadas avanzadas...")
    
    try:
        # Obtener lista de columnas usando la forma recomendada
        columnas_tabla = list(tabla_rendimiento)
        
        # Medida: Promedio de notas (si existe campo NOTA_NUMERICA)
        if "NOTA_NUMERICA" in columnas_tabla:
            m_adv["Promedio_Notas"] = tt.agg.mean(tabla_rendimiento["NOTA_NUMERICA"])
            print("  ✅ Promedio_Notas: Calcula nota promedio")
            
            # Medida: Tasa de aprobación (notas >= 5.0)
            m_adv["Tasa_Aprobacion"] = tt.agg.mean(
                tt.where(tabla_rendimiento["NOTA_NUMERICA"] >= 5.0, 1.0, 0.0)
            )
            print("  ✅ Tasa_Aprobacion: Porcentaje de aprobados")
            
            # Medida: Estudiantes con excelencia (notas >= 9.0)
            m_adv["Excelencia_Academica"] = tt.agg.mean(
                tt.where(tabla_rendimiento["NOTA_NUMERICA"] >= 9.0, 1.0, 0.0)
            )
            print("  ✅ Excelencia_Academica: Porcentaje con notas >= 9.0")
            
            # Medida: Total de evaluaciones (contando registros con notas no nulas)
            m_adv["Total_Evaluaciones"] = tt.agg.count_distinct(tabla_rendimiento["ID_EXPEDIENTE_ACADEMICO"])
            print("  ✅ Total_Evaluaciones: Cuenta todas las evaluaciones")
        
        # Medida: Estudiantes únicos evaluados
        m_adv["Estudiantes_Evaluados"] = tt.agg.count_distinct(tabla_rendimiento["ID_ALUMNO"])
        print("  ✅ Estudiantes_Evaluados: Cuenta estudiantes únicos")
        
        # Medidas adicionales basadas en las columnas disponibles
        m_adv["Total_Creditos"] = tt.agg.sum(tabla_rendimiento["CREDITOS"])
        print("  ✅ Total_Creditos: Suma total de créditos")
        
        m_adv["Promedio_Creditos"] = tt.agg.mean(tabla_rendimiento["CREDITOS"])
        print("  ✅ Promedio_Creditos: Promedio de créditos por evaluación")
        
        m_adv["Edad_Promedio"] = tt.agg.mean(tabla_rendimiento["EDAD"])
        print("  ✅ Edad_Promedio: Edad promedio de estudiantes")
        
        print("\n🎯 Medidas avanzadas configuradas exitosamente")
        
    except Exception as e:
        print(f"⚠️ Algunas medidas no se pudieron crear: {e}")
        print("💡 Esto puede deberse a problemas de sintaxis en atoti")

🚀 Creando medidas calculadas avanzadas...
  ✅ Promedio_Notas: Calcula nota promedio
  ✅ Tasa_Aprobacion: Porcentaje de aprobados
  ✅ Excelencia_Academica: Porcentaje con notas >= 9.0
  ✅ Total_Evaluaciones: Cuenta todas las evaluaciones
  ✅ Estudiantes_Evaluados: Cuenta estudiantes únicos
  ✅ Total_Creditos: Suma total de créditos
  ✅ Promedio_Creditos: Promedio de créditos por evaluación
  ✅ Edad_Promedio: Edad promedio de estudiantes

🎯 Medidas avanzadas configuradas exitosamente

### 🔬 Consultas MDX Avanzadas

Realizaremos consultas complejas que combinen múltiples dimensiones y apliquen filtros sofisticados.

In [95]:
# 🚀 CONSULTA AVANZADA 1: Análisis multi-dimensional
if 'cubo_rendimiento' in locals():
    print("🚀 CONSULTA AVANZADA: Análisis de rendimiento por múltiples dimensiones")
    
    try:
        # Buscar niveles relevantes automáticamente
        nivel_curso = None
        nivel_asignatura = None
        
        for nivel_key in l_adv.keys():
            if 'CURSO' in str(nivel_key).upper() and nivel_curso is None:
                nivel_curso = l_adv[nivel_key]
                print(f"🎯 Nivel temporal: {nivel_key}")
            elif 'ASIGNATURA' in str(nivel_key).upper() and nivel_asignatura is None:
                nivel_asignatura = l_adv[nivel_key]
                print(f"🎯 Nivel asignatura: {nivel_key}")
        
        if nivel_curso is not None and nivel_asignatura is not None:
            # Consulta con múltiples dimensiones
            resultado_avanzado = cubo_rendimiento.query(
                m_adv["Estudiantes_Evaluados"],
                m_adv["Total_Evaluaciones"],
                levels=[nivel_curso, nivel_asignatura],
                include_totals=True
            )
            
            print("\n✅ Resultado del análisis multi-dimensional:")
            display(resultado_avanzado.head(10))  # Mostrar solo primeros 10 resultados
            
            print("\n🔍 Interpretación:")
            print("  - Filas: Combinaciones de curso académico y asignatura")
            print("  - Columnas: Diferentes medidas calculadas")
            print("  - Total: Agregaciones generales")
            
        else:
            print("⚠️ No se encontraron niveles adecuados para la consulta avanzada")
            print(f"Nivel curso encontrado: {nivel_curso is not None}")
            print(f"Nivel asignatura encontrado: {nivel_asignatura is not None}")
            
    except Exception as e:
        print(f"❌ Error en consulta avanzada: {e}")
        print(f"Tipo de error: {type(e)}")
        import traceback
        traceback.print_exc()

🚀 CONSULTA AVANZADA: Análisis de rendimiento por múltiples dimensiones
🎯 Nivel asignatura: ('Asignaturas', 'NOMBRE_ASIGNATURA', 'NOMBRE_ASIGNATURA')
🎯 Nivel temporal: ('CursosAcademicos', 'NOMBRE_CURSO_ACADEMICO', 'NOMBRE_CURSO_ACADEMICO')

✅ Resultado del análisis multi-dimensional:

                                                             Estudiantes_Evaluados  \
NOMBRE_CURSO_ACADEMICO NOMBRE_ASIGNATURA
<NA>                   <NA>                                                    100
2010/2011              <NA>                                                     47
                       Algoritmos Avanzada                                       1
                       Algoritmos General                                        1
                       Analítica General Computacional                           1
                       Arqueología II                                            1
                       Bases de Datos                                            1
                       Bioquímica Fundamental Computacional                      1
                       Botánica                                                  1
                       Cirugía                                                   1

                                                             Total_Evaluaciones
NOMBRE_CURSO_ACADEMICO NOMBRE_ASIGNATURA
<NA>                   <NA>                                                1000
2010/2011              <NA>                                                  61
                       Algoritmos Avanzada                                    1
                       Algoritmos General                                     1
                       Analítica General Computacional                        1
                       Arqueología II                                         1
                       Bases de Datos                                         1
                       Bioquímica Fundamental Computacional                   1
                       Botánica                                               1
                       Cirugía                                                1

🔍 Interpretación:
  - Filas: Combinaciones de curso académico y asignatura
  - Columnas: Diferentes medidas calculadas
  - Total: Agregaciones generales

In [96]:
# 🚀 CONSULTA AVANZADA 2: Con filtros y ordenamiento
if 'cubo_rendimiento' in locals() and 'Promedio_Notas' in m_adv:
    print("🚀 CONSULTA CON FILTROS AVANZADOS")
    
    try:
        # Consulta filtrada para asignaturas con buen rendimiento
        resultado_filtrado = cubo_rendimiento.query(
            m_adv["Promedio_Notas"],
            m_adv["Tasa_Aprobacion"],
            m_adv["Estudiantes_Evaluados"],
            levels=[nivel_asignatura] if 'nivel_asignatura' in locals() else [],
            filter=(
                (m_adv["Estudiantes_Evaluados"] >= 5) &  # Solo asignaturas con suficientes estudiantes
                (m_adv["Promedio_Notas"] >= 6.0)         # Solo asignaturas con buen rendimiento
            ),
            include_totals=False
        )
        
        print("\n✅ Asignaturas con buen rendimiento (promedio ≥ 6.0 y ≥ 5 estudiantes):")
        display(resultado_filtrado)
        
        print("\n🎯 Técnicas avanzadas aplicadas:")
        print("  - Filtros compuestos con operadores lógicos (&)")
        print("  - Criterios múltiples de selección")
        print("  - Exclusión de totales para focus en detalles")
        
    except Exception as e:
        print(f"❌ Error en consulta filtrada: {e}")
        print("💡 Posible causa: Medidas calculadas no disponibles")

🚀 CONSULTA CON FILTROS AVANZADOS

✅ Asignaturas con buen rendimiento (promedio ≥ 6.0 y ≥ 5 estudiantes):

,Promedio_Notas,Tasa_Aprobacion,Estudiantes_Evaluados
NOMBRE_ASIGNATURA,,,
Contabilidad Especial,6.11,.67,9
Derecho Administrativo,7.33,1.00,6
Derecho Penal,6.33,.83,12
Farmacología,7.17,.67,6
Finanzas Avanzada,6.33,.67,6
Fisicoquímica,6.29,1.00,7
Gramática Aplicada,6.40,.60,5
Lingüística II para Científicos,6.00,.83,5
Programación,6.50,.62,8
Semántica III,6.40,.80,5
Zoología Avanzada,7.20,1.00,5
Óptica Avanzada,6.40,.80,5

🎯 Técnicas avanzadas aplicadas:
  - Filtros compuestos con operadores lógicos (&)
  - Criterios múltiples de selección
  - Exclusión de totales para focus en detalles

## 🛠️ Troubleshooting y Optimización

### ❌ Errores Comunes y Soluciones

1. **Error de conexión**: Verificar credenciales y conectividad
2. **Tablas vacías**: Confirmar que existen datos en el esquema
3. **Referencias incorrectas**: Validar nombres de columnas
4. **Consultas lentas**: Aplicar filtros para reducir volumen de datos

### 🔧 Optimizaciones para Producción

- **Indexación**: Crear índices en columnas de unión
- **Particionamiento**: Dividir tablas grandes por períodos
- **Caching**: Configurar caché para consultas frecuentes
- **Agregaciones**: Pre-calcular métricas comunes

In [ ]:
# 🔧 FUNCIÓN DE DIAGNÓSTICO
def diagnosticar_cubo(cubo, nombre_cubo):
    """
    Función de diagnóstico para validar la configuración del cubo.
    """
    print(f"🔍 DIAGNÓSTICO DE {nombre_cubo}:")
    print(f"  📊 Jerarquías: {len(cubo.hierarchies)}")
    print(f"  📈 Medidas: {len(cubo.measures)}")
    print(f"  🧮 Niveles: {len(cubo.levels)}")
    
    # Verificar si hay datos
    try:
        total_registros = cubo.query(cubo.measures["contributors.COUNT"])
        print(f"  📋 Registros totales: {total_registros.iloc[0, 0]}")
    except:
        print("  ⚠️ No se pudo determinar el número de registros")
    
    print("  ✅ Cubo operativo\n")

# Diagnosticar cubos creados
if 'cubo_academico' in locals():
    diagnosticar_cubo(cubo_academico, "CUBO ACADÉMICO BÁSICO")

if 'cubo_rendimiento' in locals():
    diagnosticar_cubo(cubo_rendimiento, "CUBO DE RENDIMIENTO AVANZADO")

## 🎓 Resumen y Próximos Pasos

### ✅ Lo que Aprendiste

**🔰 Nivel Básico:**
- Qué es Atoti y el análisis multidimensional
- Conceptos de cubos, dimensiones y medidas
- Consultas MDX básicas
- Visualizaciones interactivas simples

**🚀 Nivel Avanzado:**
- Integración de múltiples tablas
- Medidas calculadas complejas
- Consultas con filtros avanzados
- Troubleshooting y optimización

### 🔜 Siguientes Notebooks
1. **Consultas MDX Básicas**: Profundizar en sintaxis MDX
2. **Cubos Multidimensionales**: Diseño avanzado de cubos
3. **Consultas MDX Avanzadas**: Funciones especializadas
4. **Dashboards Interactivos**: Visualizaciones empresariales

### 🏃‍♂️ Ejercicios Prácticos

**Para Practicar:**
1. Crear una consulta que muestre estudiantes por año académico
2. Implementar una medida de "estudiantes en riesgo" (promedio < 5.0)
3. Diseñar un dashboard para el decano de una facultad
4. Optimizar consultas para grandes volúmenes de datos

---

**¡Felicitaciones! 🎉 Has completado la introducción a Atoti y MDX.**